# Generated by Django 5.1.7 on 2025-10-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, verbose_name='商品名称')),
                ('product_type', models.IntegerField(verbose_name='商品类型')),
                ('thumbnail', models.TextField(blank=True, verbose_name='商品小图')),
                ('banners', models.TextField(blank=True, verbose_name='banner图')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品价格')),
                ('origin_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='商品原价')),
                ('color', models.CharField(blank=True, max_length=100, verbose_name='商品颜色')),
                ('inventory', models.IntegerField(blank=True, default=0, verbose_name='库存')),
                ('norm', models.IntegerField(blank=True, default=1, verbose_name='规格')),
                ('brief', models.CharField(blank=True, max_length=200, verbose_name='商品简介')),
                ('describe', models.TextField(blank=True, verbose_name='商品描述')),
            ],
            options={
                'db_table': 'pd_products',
            },
        ),
    ]
