# Generated by Django 5.1.7 on 2025-10-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.CharField(max_length=48, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='订单金额')),
                ('buy_num', models.IntegerField(default=0, verbose_name='订单数量')),
                ('product_name', models.CharField(default='', max_length=50, verbose_name='商品名称')),
                ('product_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='商品单价')),
                ('activity_id', models.IntegerField(blank=True, null=True, verbose_name='关联活动ID')),
                ('status', models.IntegerField(default=0, verbose_name='订单状态')),
                ('remarks', models.CharField(blank=True, max_length=200, verbose_name='备注')),
            ],
            options={
                'db_table': 'pd_orders',
            },
        ),
    ]
