# Generated by Django 5.1.7 on 2025-10-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_name', models.CharField(max_length=50, verbose_name='活动名称')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('remarks', models.CharField(blank=True, max_length=200, verbose_name='备注')),
            ],
            options={
                'db_table': 'ot_activity',
                'ordering': ('id',),
            },
        ),
    ]
