# Generated by Django 5.1.7 on 2025-10-25 12:14

import common.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_name', models.CharField(max_length=50, verbose_name='配置名')),
                ('config_val', models.CharField(blank=True, max_length=50, verbose_name='配置值')),
            ],
            options={
                'db_table': 'ot_system_config',
            },
        ),
        migrations.CreateModel(
            name='UploadImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveIntegerField(default=155)),
                ('width', models.PositiveIntegerField(default=155)),
                ('image_type', models.IntegerField(default=0)),
                ('image_url', models.ImageField(height_field='height', upload_to=common.utils.get_upload_to, width_field='width')),
            ],
            options={
                'db_table': 'ot_upload_imges',
            },
        ),
        migrations.CreateModel(
            name='GlobalClassify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classify_name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='分类标识')),
                ('index', models.IntegerField(default=0, verbose_name='排序')),
                ('classify_image', models.CharField(blank=True, default='', max_length=200, verbose_name='分类图片')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='assets.globalclassify')),
            ],
            options={
                'db_table': 'ot_classify',
                'ordering': ('id', 'index'),
            },
        ),
    ]
