# Generated by Django 5.1.7 on 2025-12-14 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimages',
            name='image_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
