# Generated by Django 5.1.7 on 2025-12-14 02:10

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_uploadimages_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimages',
            name='image_url',
            field=models.ImageField(blank=True, height_field='height', null=True, upload_to=common.utils.get_upload_to, width_field='width'),
        ),
    ]
