# Generated by Django 5.1.7 on 2025-10-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=100, verbose_name='智能体名称')),
                ('sex', models.IntegerField(blank=True, null=True, verbose_name='性别')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('description', models.TextField(verbose_name='描述')),
                ('brief', models.CharField(max_length=100, verbose_name='一句话简介')),
                ('prompt', models.TextField(verbose_name='提示词')),
                ('avatar', models.CharField(max_length=300, verbose_name='头像')),
                ('avatar_bg', models.CharField(blank=True, max_length=300, verbose_name='背景图片')),
                ('avatar_wait', models.CharField(blank=True, max_length=300, verbose_name='等待动画')),
                ('avatar_speaking', models.CharField(blank=True, max_length=300, verbose_name='说话动画')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('salutation', models.TextField(blank=True, verbose_name='开场白')),
                ('salutation_audio', models.CharField(blank=True, max_length=300, verbose_name='开场白声音')),
                ('salutation_new', models.TextField(blank=True, default='', verbose_name='新对话开场白')),
                ('salutation_new_audio', models.CharField(blank=True, max_length=300, verbose_name='新对话开场白声音')),
                ('max_round', models.IntegerField(blank=True, default=0, verbose_name='最大回合数')),
                ('model', models.CharField(max_length=50, null=True, verbose_name='AI模型')),
                ('tts', models.CharField(max_length=50, null=True, verbose_name='语音合成')),
                ('asr', models.CharField(max_length=50, null=True, verbose_name='语音识别')),
                ('voice_role', models.CharField(max_length=50, null=True, verbose_name='音色')),
                ('emotion', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='音色情感')),
                ('voice_rate', models.IntegerField(default=0, verbose_name='语速')),
                ('pitch_rate', models.IntegerField(default=0, verbose_name='语调')),
                ('temperature', models.CharField(blank=True, max_length=10, verbose_name='温度')),
            ],
            options={
                'db_table': 'ai_agent',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='AIModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, verbose_name='模型名称')),
                ('model_code', models.CharField(max_length=50, verbose_name='模型编码')),
                ('model_type', models.CharField(max_length=30, verbose_name='模型类型')),
                ('base_url', models.TextField(blank=True, verbose_name='调用URL')),
                ('api_key', models.TextField(blank=True, verbose_name='API密钥')),
                ('app_key', models.TextField(blank=True, verbose_name='应用ID')),
                ('accesskey_id', models.TextField(blank=True, verbose_name='密钥ID')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='是否启用')),
                ('call_count', models.IntegerField(blank=True, default=2, verbose_name='最大并发')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'db_table': 'ai_models',
                'ordering': ('sort',),
            },
        ),
        migrations.CreateModel(
            name='Assess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assess_name', models.CharField(max_length=50, verbose_name='维度名称')),
                ('prompt', models.TextField(verbose_name='提示词')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'ai_defy_assess',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='DefyAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_round', models.IntegerField(default=0, verbose_name='最大回合')),
                ('description', models.TextField(verbose_name='练习目标')),
                ('count', models.IntegerField(default=10, verbose_name='练习人数')),
                ('shelf_status', models.BooleanField(default=True, verbose_name='上架状态')),
                ('index', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'db_table': 'ai_defy_agent',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='DefyDialog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=10, verbose_name='角色')),
                ('emotion', models.CharField(blank=True, default='', max_length=10, verbose_name='情绪')),
                ('content', models.TextField(verbose_name='内容')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'ai_defy_dialog',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=10, verbose_name='角色')),
                ('content', models.TextField(verbose_name='内容')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'ai_dialog',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_type', models.IntegerField(blank=True, default=1, verbose_name='记忆类型')),
                ('abstract', models.TextField(blank=True, verbose_name='记忆摘要')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'ai_memory',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talkId', models.CharField(blank=True, max_length=32, verbose_name='会话ID')),
                ('round', models.IntegerField(blank=True, default=0, verbose_name='回合')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'ai_topic',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='UserDefy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField(blank=True, default=0, verbose_name='已挑战回合')),
                ('defy_status', models.IntegerField(blank=True, default=0, verbose_name='状态')),
                ('result_status', models.CharField(blank=True, max_length=30, null=True, verbose_name='结果状态')),
                ('result', models.TextField(blank=True, null=True, verbose_name='评估结果')),
                ('vip_check', models.BooleanField(default=False, verbose_name='做为VIP查看过')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('lastTime', models.DateTimeField(blank=True, null=True, verbose_name='最后时间')),
            ],
            options={
                'db_table': 'ai_user_defy',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='VoiceRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_name', models.CharField(max_length=100, verbose_name='音色名称')),
                ('voice_code', models.CharField(max_length=50, verbose_name='音色编码')),
                ('is_emotion', models.BooleanField(default=False, verbose_name='是否多情感')),
                ('voice_type', models.IntegerField(default=0, verbose_name='音色类型')),
                ('audio_url', models.TextField(blank=True, verbose_name='试听链接')),
            ],
            options={
                'db_table': 'ai_voice_role',
                'ordering': ('id',),
            },
        ),
    ]
