# Generated by Django 5.1.7 on 2025-10-25 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AI', '0001_initial'),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='classify',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.globalclassify', verbose_name='所属分类'),
        ),
        migrations.AddField(
            model_name='defyagent',
            name='agent_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='AI.agent', verbose_name='所属智能体'),
        ),
        migrations.AddField(
            model_name='defyagent',
            name='assess',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='AI.assess', verbose_name='结果评估维度'),
        ),
        migrations.AddField(
            model_name='defyagent',
            name='classify',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.globalclassify', verbose_name='所属分类'),
        ),
    ]
