# Generated by Django 5.1.7 on 2025-12-14 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='avatar_speaking',
            field=models.CharField(blank=True, max_length=3000, verbose_name='说话动画'),
        ),
    ]
